# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "congo"

defaultAppearance = "dark"

autoSwitchAppearance = false

enableSearch = true

enableCodeCopy = true

darkToggle = true
#logo = "/img/author.jpg"

mainSections = ["HTB"]

[header]
  layout = "basic"

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true

[footer]
  showScrollToTop = true
  showAppearanceSwitcher = true

[article]
  showDate = false
  showDateUpdated = false
  showAuthor = false
  dateFormat = "2 January 2006"
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editAppendPath = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showComments = false
  sharingLinks = ["twitter", "reddit", "linkedin"]

[list]
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false
  groupByYear = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true




